Reanimated 2.4 - fix error in Incubator.TouchableOpacity (#1831)
Error: Interpolation input and output should contain at least two values.
(cherry picked from commit c8b03e1194f7fde1ad04aab62405ab60ec33c50c)