TypeError: undefined is not an object (evaluating 'this.styles.topContainer') (#1716)
* fix typo react-native-gesutre-handler -> react-native-gesture-handler

* generateStyles is not called yet

so it caused npe `this.styles.topContainer` on line 112.